#!/bin/bash

failed=0

for i in isos profile random sample ni56 big_net;
do
    cd "$i" || exit 1
    if ./test 2>&1 >/dev/null; then
        echo "$i passed"
    else
        echo "$i failed"
        failed=1
    fi
    cd ../
done

exit $failed
